[build]
builder = "dockerfile"

[deploy]
startCommand = "./start_services.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "api"
internalPort = 8000
processes = 4
healthcheckPath = "/health"

[[services]]
name = "mlflow"
internalPort = 5004
processes = 1
healthcheckPath = "/"

[[services]]
name = "dashboard"
internalPort = 8501
processes = 1
healthcheckPath = "/"

[environments]
production = { }
staging = { }