services:
  - type: web
    name: delfos-biomarkers
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "./start_services.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: PORT
        value: "8000"
      - key: MLFLOW_TRACKING_URI
        value: "https://delfos-biomarkers.onrender.com/mlflow"
      - key: RENDER
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: delfos-data
      mountPath: /app
      sizeGB: 10
    envs:
      - key: NODE_ENV
        value: "production"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"

# Configuración de base de datos PostgreSQL
databases:
  - name: delfos-postgres
    databaseName: delfos_medical
    user: delfos_user
    ipAllowList: [] # Solo accesible desde otros servicios de Render

# Configuración de Redis para caché
redis:
  - name: delfos-redis
    ipAllowList: [] # Solo accesible desde otros servicios de Render