services:
  # API REST del Sistema Predictivo de Diabetes
  - type: web
    name: diabetes-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8002
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: MLFLOW_TRACKING_URI
        value: file:///app/outputs/mlruns
      - key: MLFLOW_HOST
        value: 0.0.0.0
      - key: MLFLOW_PORT
        value: 5002

  # Interfaz Web Streamlit
  - type: web
    name: diabetes-streamlit
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run web_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    healthCheckPath: /
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: MLFLOW_TRACKING_URI
        value: file:///app/outputs/mlruns
      - key: API_BASE_URL
        value: https://delfosa1c8-3.onrender.com

  # Sistema MLflow UI
  - type: web
    name: diabetes-mlflow
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "mkdir -p /app/outputs/mlruns && mlflow ui --backend-store-uri file:///app/outputs/mlruns --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    healthCheckTimeout: 60
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: MLFLOW_TRACKING_URI
        value: file:///app/outputs/mlruns
      - key: MLFLOW_HOST
        value: 0.0.0.0
      - key: MLFLOW_PORT
        value: 5002
      - key: MLFLOW_BACKEND_STORE_URI
        value: file:///app/outputs/mlruns
      - key: HOME
        value: /app

  # Base de datos PostgreSQL
  - type: pserv
    name: diabetes-db
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: diabetes-db
          property: connectionString