services:
  - type: web
    name: delfos-biomarkers
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "./start_services.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: PORT
        value: "8000"
      - key: RENDER
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: delfos-data
      mountPath: /app
      sizeGB: 10
    envs:
      - key: NODE_ENV
        value: "production"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"