#!/usr/bin/env python3
"""
INSTRUCCIONES PASO A PASO PARA RENDER - CON CAPTURAS DE PANTALLA
"""

print("🖥️ INSTRUCCIONES VISUALES PARA RENDER")
print("="*60)

print("\n📍 PASO 1: ENTRAR AL DASHBOARD")
print("   1. Abre: https://dashboard.render.com")
print("   2. Busca tu repositorio conectado")
print("   3. Haz clic en 'Create Web Service'")
print("   ")
print("   📋 DEBE VERSE ASÍ:")
print("   +-------------------------------+")
print("   | [Tu Repositorio]             |")
print("   |                              |")
print("   | • Create Web Service         |")
print("   +-------------------------------+")

print("\n📍 PASO 2: CONFIGURACIÓN BÁSICA")
print("   ")
print("   📝 NOMBRE DEL SERVICIO:")
print("   +-------------------------------+")
print("   | diabetes-api                 |")
print("   +-------------------------------+")
print("   ")
print("   ⚙️ RUNTIME:")
print("   +-------------------------------+")
print("   | Python 3                     |")
print("   +-------------------------------+")

print("\n📍 PASO 3: COMANDOS DE BUILD Y START")
print("   ")
print("   🔧 BUILD COMMAND:")
print("   +-------------------------------+")
print("   | pip install -r requirements.txt|")
print("   +-------------------------------+")
print("   ")
print("   🚀 START COMMAND:")
print("   +-------------------------------+")
print("   | python api.py --host 0.0.0.0 |")
print("   | --port $PORT                 |")
print("   +-------------------------------+")

print("\n📍 PASO 4: VARIABLES DE ENTORNO")
print("   ")
print("   🌍 ENVIRONMENT VARIABLES:")
print("   Haz clic en 'Add Environment Variable'")
print("   ")
print("   📝 COPIA Y PEGA ESTAS VARIABLES:")
print("   ")
print("   1️⃣ ENVIRONMENT=production")
print("   2️⃣ DEBUG=false")
print("   3️⃣ LOG_LEVEL=INFO")
print("   4️⃣ SECRET_KEY=diabetes-secret-key-2025-super-seguro")
print("   5️⃣ JWT_SECRET_KEY=diabetes-jwt-secret-key-2025-super-seguro")
print("   6️⃣ API_HOST=0.0.0.0")
print("   7️⃣ API_PORT=8002")
print("   8️⃣ STREAMLIT_SERVER_ADDRESS=0.0.0.0")
print("   9️⃣ STREAMLIT_SERVER_PORT=8501")
print("   🔟 STREAMLIT_SERVER_HEADLESS=true")
print("   1️⃣1️⃣ MLFLOW_TRACKING_URI=file:///app/outputs/mlruns")
print("   1️⃣2️⃣ MLFLOW_HOST=0.0.0.0")
print("   1️⃣3️⃣ MLFLOW_PORT=5002")

print("\n📍 PASO 5: BASE DE DATOS")
print("   ")
print("   💾 DATABASE:")
print("   +-------------------------------+")
print("   | [✓] Create PostgreSQL database|")
print("   |                              |")
print("   | Nombre: diabetes-db          |")
print("   +-------------------------------+")

print("\n📍 PASO 6: DESPLEGAR")
print("   ")
print("   🚀 BOTÓN FINAL:")
print("   +-------------------------------+")
print("   | [Create Web Service]         |")
print("   +-------------------------------+")
print("   ")
print("   ⏱️ ESPERA 3-5 MINUTOS")
print("   ")
print("   ✅ ¡LISTO!")

print("\n🌐 URLS FINALES:")
print("   • API: https://diabetes-api.onrender.com")
print("   • Docs: https://diabetes-api.onrender.com/docs")
print("   • Health: https://diabetes-api.onrender.com/health")

print("\n💡 CONSEJOS IMPORTANTES:")
print("   • Copia las variables EXACTAMENTE como están")
print("   • El nombre del servicio DEBE ser 'diabetes-api'")
print("   • No cambies los comandos de build y start")
print("   • La base de datos se crea automáticamente")

print("\n🎯 ¡SIGUE ESTOS PASOS Y TU API ESTARÁ FUNCIONANDO!")